language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer global require "fxp/composer-asset-plugin"
  - travis_retry symfony/yaml
  - travis_retry composer require fabpot/php-cs-fixer
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpenv config-rm xdebug.ini || return 0
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover